### ISSUE TITLE
iOS TestFlight Request

### ISSUE THREAD

**Issue by jeffreybergier** [jeffreybergier/Hipstapaper#1]
The TestFlight Link is Here:

https://testflight.apple.com/join/V1f2j5Jd

**Comment by y4rr** [comment]
Hi. Please add me to the iOS TestFlight.

**Comment by jeffreybergier** [comment]
@y4rr Ok. I just submitted a new build. Once its approved for TestFlight, I'll post the public testflight link here.

**Comment by jeffreybergier** [comment]
@y4rr Ok. The testflight link is pasted (above)

**Comment by y4rr** [comment]
@y4rr Thanks!
